"use client";

import Link from "next/link";
import { FormEvent, useMemo, useState } from "react";
import { DemoCabinetSwitcher } from "@/components/demo/DemoCabinetSwitcher";
import { patchDemoContractor, resetDemoContractorState } from "@/lib/demo/contractor-demo-api";
import { demoContractorProjectStatuses, type DemoContractorAction, type DemoContractorState } from "@/lib/demo/types";

type View = "overview" | "team" | "requests" | "projects" | "tasks" | "messages" | "documents" | "notifications";
const navigation: { id: View; label: string }[] = [{ id: "overview", label: "Огляд" }, { id: "team", label: "Команда" }, { id: "requests", label: "Заявки" }, { id: "projects", label: "Проєкти" }, { id: "tasks", label: "Завдання" }, { id: "messages", label: "Чат" }, { id: "documents", label: "Документи" }, { id: "notifications", label: "Сповіщення" }];
const money = (value: number | null) => value === null ? "Не вказано" : `${new Intl.NumberFormat("uk-UA").format(value)} грн`;

export function DemoContractorCabinetApp({ initialData, stateWarning }: { initialData: DemoContractorState; stateWarning?: string }) {
  const [state, setState] = useState(initialData); const [view, setView] = useState<View>("overview"); const [pending, setPending] = useState<string>(); const [notice, setNotice] = useState(stateWarning); const [error, setError] = useState<string>(); const [resetOpen, setResetOpen] = useState(false); const [messageProjectId, setMessageProjectId] = useState(initialData.projects[0]?.id ?? ""); const [messageBody, setMessageBody] = useState("");
  const memberName = useMemo(() => new Map(state.team.map((item) => [item.id, item.name])), [state.team]);
  async function act(action: DemoContractorAction, key: string, success: string) { setPending(key); setError(undefined); try { setState(await patchDemoContractor(action)); setNotice(success); } catch (reason) { setError(reason instanceof Error ? reason.message : "Не вдалося зберегти зміни."); } finally { setPending(undefined); } }
  async function send(event: FormEvent) { event.preventDefault(); if (!messageProjectId || !messageBody.trim()) return; await act({ type: "send_message", projectId: messageProjectId, body: messageBody }, "message", "Демонстраційне повідомлення надіслано."); setMessageBody(""); }
  async function reset() { setPending("reset"); setError(undefined); try { const next = await resetDemoContractorState(); setState(next); setMessageProjectId(next.projects[0]?.id ?? ""); setNotice("Демонстраційні дані підрядника відновлено."); setResetOpen(false); } catch (reason) { setError(reason instanceof Error ? reason.message : "Не вдалося скинути демоверсію."); } finally { setPending(undefined); } }
  return <section className="demo-contractor-cabinet">
    <aside className="demo-contractor-side"><Link href="/">BudPomich <span>Кабінет підрядника</span></Link><nav aria-label="Розділи демокабінету підрядника">{navigation.map((item, index) => <button className={view === item.id ? "active" : ""} key={item.id} onClick={() => setView(item.id)} type="button"><span>{String(index + 1).padStart(2, "0")}</span>{item.label}</button>)}</nav><small>{state.profile.companyName}<br />{state.profile.city}</small></aside>
    <main className="demo-contractor-main">
      <DemoCabinetSwitcher currentRole="contractor" />
      <aside className="demo-contractor-banner"><div><strong>Демонстраційний режим</strong><p>Ви переглядаєте заповнений приклад кабінету підрядника. Усі працівники, заявки, проєкти, фінанси та повідомлення є демонстраційними.</p></div><nav aria-label="Дії демоверсії підрядника"><Link href="/auth/register">Створити акаунт</Link><button onClick={() => setResetOpen(true)} type="button">Скинути демоверсію</button><Link href="/">Вийти</Link></nav></aside>
      {(notice || error) && <div className={`demo-contractor-feedback ${error ? "error" : ""}`} role={error ? "alert" : "status"}>{error ?? notice}</div>}
      <header className="demo-contractor-head"><div><span>Підрядник · команда · проєкти</span><h1>{state.profile.companyName}</h1><p>{state.profile.description || `Команда підрядника у місті ${state.profile.city}`}</p></div><strong>{state.profile.city}</strong></header>
      {view === "overview" && <section><h2>Огляд компанії</h2><div className="demo-contractor-stats"><article><strong>{state.statistics.activeProjects}</strong><span>Активні проєкти</span></article><article><strong>{state.statistics.teamMembers}</strong><span>Майстри</span></article><article><strong>{state.statistics.availableMembers}</strong><span>Доступні майстри</span></article><article><strong>{money(state.statistics.monthlyRevenue)}</strong><span>Оборот за місяць</span></article><article><strong>{state.statistics.completedProjects}</strong><span>Завершені проєкти</span></article></div><h2>Активні роботи</h2><div className="demo-contractor-project-grid">{state.projects.slice(0, 3).map((project) => <article key={project.id}><span>{project.status}</span><h3>{project.title}</h3><progress max="100" value={project.progress}>{project.progress}%</progress><strong>{project.progress}%</strong><button onClick={() => setView("projects")} type="button">Відкрити проєкт</button></article>)}{!state.projects.length && <p>Проєктів поки немає.</p>}</div></section>}
      {view === "team" && <section><h2>Команда майстрів</h2><div className="demo-contractor-team-grid">{state.team.map((member) => <article key={member.id}><h3>{member.name}</h3><p>{member.specialty}</p><label>Статус<select disabled={Boolean(pending)} value={member.status} onChange={(event) => act({ type: "update_team_member_status", teamMemberId: member.id, status: event.target.value as typeof member.status }, `team:${member.id}`, "Статус майстра оновлено.")}><option value="available">Доступний</option><option value="busy">Зайнятий</option><option value="unavailable">Недоступний</option></select></label><span>Завантаження: {member.workload}%</span><progress max="100" value={member.workload}>{member.workload}%</progress><small>{member.projectId ? `Проєкт: ${state.projects.find((project) => project.id === member.projectId)?.title ?? member.projectId}` : "Проєкт не призначено"}</small></article>)}{!state.team.length && <p>Команда поки порожня.</p>}</div></section>}
      {view === "requests" && <section><h2>Заявки клієнтів</h2><div className="demo-contractor-list">{(state.requests ?? []).map((request) => <article key={request.id}><div><h3>{request.title}</h3><p>{request.clientName} · {request.status}</p></div><strong>{money(request.budget)}</strong></article>)}{!(state.requests ?? []).length && <p>Заявок поки немає.</p>}</div></section>}
      {view === "projects" && <section><h2>Проєкти</h2><div className="demo-contractor-project-grid">{state.projects.map((project) => <article key={project.id}><h3>{project.title}</h3><p>Бюджет: {money(project.budget)} · Термін: {project.deadline || "не вказано"}</p><label>Статус<select disabled={Boolean(pending)} value={project.status} onChange={(event) => act({ type: "update_project_status", projectId: project.id, status: event.target.value as typeof project.status }, `project:${project.id}`, "Статус проєкту оновлено.")}>{demoContractorProjectStatuses.map((status) => <option key={status}>{status}</option>)}</select></label><label>Прогрес: {project.progress}%<input disabled={Boolean(pending)} min="0" max="100" step="5" type="range" value={project.progress} onChange={(event) => act({ type: "update_project_progress", projectId: project.id, progress: Number(event.target.value) }, `progress:${project.id}`, "Прогрес проєкту оновлено.")} /></label><label>Відповідальний<select disabled={Boolean(pending) || !state.team.length} value={project.teamMemberId} onChange={(event) => act({ type: "assign_team_member", projectId: project.id, teamMemberId: event.target.value }, `assign:${project.id}`, "Майстра призначено.")}><option value="" disabled>Оберіть майстра</option>{state.team.map((member) => <option key={member.id} value={member.id}>{member.name}</option>)}</select></label><small>{memberName.get(project.teamMemberId) || "Майстра не призначено"}</small></article>)}{!state.projects.length && <p>Проєктів поки немає.</p>}</div></section>}
      {view === "tasks" && <section><h2>Робочі завдання</h2><div className="demo-contractor-list">{(state.tasks ?? []).map((task) => <article key={task.id}><div><h3>{task.title}</h3><p>{state.projects.find((project) => project.id === task.projectId)?.title ?? "Проєкт не вказано"}</p></div><select disabled={Boolean(pending)} value={task.status} onChange={(event) => act({ type: "update_task_status", taskId: task.id, status: event.target.value as typeof task.status }, `task:${task.id}`, "Статус завдання оновлено.")}><option value="new">Нове</option><option value="in_progress">В роботі</option><option value="completed">Завершено</option></select></article>)}{!(state.tasks ?? []).length && <p>Завдань поки немає.</p>}</div></section>}
      {view === "messages" && <section><h2>Чат за проєктами</h2><div className="demo-contractor-messages">{(state.messages ?? []).map((message) => <article className={message.senderRole === "contractor" ? "own" : ""} key={message.id}><strong>{message.sender}</strong><p>{message.body}</p><time>{message.createdAt ? new Date(message.createdAt).toLocaleString("uk-UA") : ""}</time></article>)}{!(state.messages ?? []).length && <p>Повідомлень поки немає.</p>}</div><form className="demo-contractor-composer" onSubmit={send}><label>Проєкт<select value={messageProjectId} onChange={(event) => setMessageProjectId(event.target.value)}>{state.projects.map((project) => <option key={project.id} value={project.id}>{project.title}</option>)}</select></label><label>Повідомлення<textarea maxLength={2000} rows={3} value={messageBody} onChange={(event) => setMessageBody(event.target.value)} /></label><button disabled={Boolean(pending) || !messageProjectId || !messageBody.trim()} type="submit">Надіслати</button></form></section>}
      {view === "documents" && <section><h2>Документи</h2><div className="demo-contractor-list">{(state.documents ?? []).map((document) => <article key={document.id}><div><h3>{document.title}</h3><p>{document.kind} · {state.projects.find((project) => project.id === document.projectId)?.title ?? "Без проєкту"}</p></div></article>)}{!(state.documents ?? []).length && <p>Документів поки немає.</p>}</div></section>}
      {view === "notifications" && <section><h2>Сповіщення</h2><div className="demo-contractor-list">{(state.notifications ?? []).map((notification) => <article key={notification.id}><div><h3>{notification.title}</h3><p>{notification.isRead ? "Переглянуто" : "Нове"}</p></div>{!notification.isRead && <button disabled={Boolean(pending)} onClick={() => act({ type: "mark_notification_read", notificationId: notification.id }, `notification:${notification.id}`, "Сповіщення прочитано.")} type="button">Позначити прочитаним</button>}</article>)}{!(state.notifications ?? []).length && <p>Сповіщень поки немає.</p>}</div></section>}
    </main>
    {resetOpen && <div className="demo-contractor-modal" role="presentation"><section aria-labelledby="contractor-reset-title" aria-modal="true" role="dialog"><h2 id="contractor-reset-title">Скинути демоверсію?</h2><p>Усі зміни буде скасовано, а початкові демонстраційні дані — відновлено.</p><div><button onClick={() => setResetOpen(false)} type="button">Скасувати</button><button disabled={Boolean(pending)} onClick={reset} type="button">Скинути</button></div></section></div>}
  </section>;
}
